### ISSUE TITLE
BalooThambi - diacritics

### ISSUE THREAD

**Issue by abhisheksuresh** [girish-dalvi/Baloo#13]
Hey folks!

Really great work on this lovely font. It is a very nice font. I am thoroughly enjoying the use of this. Kudos guys!

I have a question around the diacritics in tamil font while I'm using in photoshop. When I translate a word from google, lets say education: கல்வி and when I use it in illustrator/photoshop, I get the last diacritic separated from the word. It looks like this:
<img width="202" alt="screen shot 2016-09-23 at 10 24 07" src="https://cloud.githubusercontent.com/assets/11704423/18770303/f546b29e-8177-11e6-87a6-a06bece4d9a5.png">

For now I'm splitting the strings and positioning them manually and that is not quite positioning really well.

<img width="616" alt="screen shot 2016-09-23 at 10 28 17" src="https://cloud.githubusercontent.com/assets/11704423/18770376/993d8c24-8178-11e6-99a8-886049d19874.png">

I am pretty sure I am not doing something right here. Please point me in the right direction!  

Thanks in advance!
Abi

**Comment by davelab6** [comment]
http://www.thomasphinney.com/2009/01/adobe-world-ready-composer/

**Comment by abhisheksuresh** [comment]
Legend! Thanks for that. I got it to look right!

In addition to the link you shared. These links helped me for this particular dialect: https://helpx.adobe.com/illustrator/using/indic-support.html
https://www.youtube.com/watch?v=UUPlPcGGiPc

 :) Thanks @davelab6 !
