### ISSUE TITLE
Vietnamese issue

### ISSUE THREAD

**Issue by crystaltype** [girish-dalvi/Baloo#14]
https://docs.google.com/presentation/d/1zZ28HbbwfBLdQKtW1r6pCpC2uwDhEZhnye-k67x8liM/edit?usp=sharing I described the problem as seen in slide #53.

**Comment by davelab6** [comment]
![google fonts vietnamese 1](https://cloud.githubusercontent.com/assets/261579/18838704/620cab44-83d6-11e6-8979-798188b26818.png)

**Comment by girish-dalvi** [comment]
Fixed in v1.425.
