### ISSUE TITLE
u+0c9c, u+0cbc, u+0cbe and u+0cbe, u+0cbc combination issue

### ISSUE THREAD

**Issue by MayuraVerma** [girish-dalvi/Baloo#15]
u+0c9c, u+0cbc, u+0cbe combination 'ಜ಼ಾಕಿರ್' and u+0c9c, u+0cbe, u+0cbc combination 'ಜಾ಼ಕಿರ್' have issue with baloo tamma font. Please rectify.

Please check this test site for visuals
http://kannadafont.blogspot.com/2017/03/case1-u0c9c-u0cbc-u0cbe-combination.html

**Comment by girish-dalvi** [comment]
Fixed in 1.443
