### ISSUE TITLE
Baloo Tamma-Kannada issues

### ISSUE THREAD

**Issue by sridatta1** [girish-dalvi/Baloo#17]
Version 1.425
### ಕು 
![ku](https://cloud.githubusercontent.com/assets/23263723/26751971/01fbc814-4863-11e7-8c98-7c8b7e69bcfb.PNG)
correct form 
![kun](https://cloud.githubusercontent.com/assets/23263723/26751970/01bb1ea4-4863-11e7-9dd2-dc499851832d.PNG)
### ಞೀ 
Vowel sign I missing in ಞೀ
![nya](https://cloud.githubusercontent.com/assets/23263723/26751980/44292146-4863-11e7-8364-27f403274bb4.PNG)

### ಮೊ ಮೋ ಯೊ ಯೋ  ಝೊ ಝೋ
![mo yo](https://cloud.githubusercontent.com/assets/23263723/26752023/2458323e-4864-11e7-9ea4-7e464d02824d.PNG)
should not have extra ು
correct forms-
![mo](https://cloud.githubusercontent.com/assets/23263723/26752015/04bbdc50-4864-11e7-8344-5ded7e04e4a1.PNG)

###  ಘೆ ಘೇ ಘೈ ಘೊ ಘೋ ಘೌ
The headstroke shouldn't extend to the right
![ghe](https://cloud.githubusercontent.com/assets/23263723/26752195/eb937f72-4867-11e7-893d-52f58270e60c.PNG)
![gho](https://cloud.githubusercontent.com/assets/23263723/26752196/eb9c5232-4867-11e7-9585-e4d41990b570.PNG)

For consonants which don't have headstroke (ಙಞಱೞ and optionally ಣ) take special forms for signs ಾ ೆ ೇ ೈ ೊ ೋ ್
 ೞಾ ೞೆ ೞೇ ೞೈ ೞೊ ೞೋ ೞ್
 ಱಾ ಱೆ ಱೇ ಱೈ ಱೊ ಱೋ ಱ್ 
should be similar to ಞೆ ಞೇ ಙಾ etc. 
correct glyphs-
![llla](https://cloud.githubusercontent.com/assets/23263723/26752286/1268812c-486a-11e7-8c0a-677cf56ad9f8.PNG)

**Comment by girish-dalvi** [comment]
Fixed in 1.443
