### ISSUE TITLE
Baloo Tamma issues with length mark

### ISSUE THREAD

**Issue by sridatta1** [girish-dalvi/Baloo#22]
![image](https://user-images.githubusercontent.com/23263723/36352949-f9cd55e0-14e5-11e8-834d-5eb7c1418bb6.png)
in Vowel sign EE and II with subscripts.
should be as in
![image](https://user-images.githubusercontent.com/23263723/36352980-5b36c442-14e6-11e8-8805-b2658e9d7732.png)

**Comment by lianghai** [comment]
Basically, all glyphs with the length mark precomposed should be removed. The length mark is an independent structure that basically (some marginal cases might need hacks) should be left for text engines to reorder.

**Comment by sridatta1** [comment]
Hello,
Any idea when will this issue be fixed? As many are using this font currently.

**Comment by sridatta1** [comment]
Hello,
I am seeing the font being used in many places like in posters, signages in lots of shops, also in documents etc. At what time, the issue will be solved?

**Comment by girish-dalvi** [comment]
Thank you for following up. This issue has been resolved in the upgraded version of the font. Please download the latest version of this font from https://github.com/EkType/Baloo2

**Comment by sridatta1** [comment]
Thank you.
I was expecting these issues would have been fixed in the Baloo2 version. I didn't know it was just released.
