### ISSUE TITLE
BalooBhaina-Odia 

### ISSUE THREAD

**Issue by mkwiki** [girish-dalvi/Baloo#3]
ସ୍କ୍ରେ, ଶ୍ଲେ, ବ୍ଲେ, ବ୍ଳେ,ଶ୍ନୋ, ଶ୍ଟ୍ରୋ, ଗ୍ଲୋ, କ୍ଟୋ, ନ୍ୱେ and ତ୍ତ୍ଵେ is broken.
![baloo](https://cloud.githubusercontent.com/assets/16492140/12490635/8bff67f0-c09c-11e5-9489-c84100a0553c.png)

**Comment by girish-dalvi** [comment]
Fixed in 1.10
