### ISSUE TITLE
Baloo Tammudu Metrics issue

### ISSUE THREAD

**Issue by davelab6** [girish-dalvi/Baloo#30]
It looks like Baloo Tammudu has some broken metrics. Specifically when rendered with lang set to "te" (Telegu). For example: https://fonts.google.com/?subset=telugu&query=baloo. It looks like the telegu variants of several glyphs have massive advance widths.

If you TTX the file you get these warnings:
WARNING: Glyph 'matraAi.te' has a huge advance width (65486); is it intentional or an (invalid) negative value?
WARNING: Glyph 'Halant.te' has a huge advance width (65516); is it intentional or an (invalid) negative value?
WARNING: Glyph 'Lengthmark.te' has a huge advance width (65507); is it intentional or an (invalid) negative value?
WARNING: Glyph 'matraAiLengthmark.te' has a huge advance width (65534); is it intentional or an (invalid) negative value?

It's the `-webkit-locale: "te";` setting. Reproduced in a codepen:  https://codepen.io/garretrieger/pen/mdJmBrx.

**Comment by davelab6** [comment]
Can this be addressed soon? If not I'll have to get it delisted from Google Fonts until it can be fixed :/

**Comment by 4nh51rk** [comment]
#18

**Comment by 4nh51rk** [comment]
> It looks like Baloo Tammudu has some broken metrics. Specifically when rendered with lang set to "te" (Telegu). For example: https://fonts.google.com/?subset=telugu&query=baloo. It looks like the telegu variants of several glyphs have massive advance widths.
> 
> If you TTX the file you get these warnings:
> WARNING: Glyph 'matraAi.te' has a huge advance width (65486); is it intentional or an (invalid) negative value?
> WARNING: Glyph 'Halant.te' has a huge advance width (65516); is it intentional or an (invalid) negative value?
> WARNING: Glyph 'Lengthmark.te' has a huge advance width (65507); is it intentional or an (invalid) negative value?
> WARNING: Glyph 'matraAiLengthmark.te' has a huge advance width (65534); is it intentional or an (invalid) negative value?
> 
> It's the `-webkit-locale: "te";` setting. Reproduced in a codepen: https://codepen.io/garretrieger/pen/mdJmBrx.

Hi @davelab6

I raised this issue #18 to @girish-dalvi  in 2017 no fix till now :(

P.S @girish-dalvi I like the font but can't use it.

**Comment by girish-dalvi** [comment]
Thank you for following up. This issue has been resolved in the upgraded version of the font. Please download the latest version of this font from https://github.com/EkType/Baloo2
