### ISSUE TITLE
Release package suggestions

### ISSUE THREAD

**Issue by davelab6** [girish-dalvi/Baloo#6]
After looking at `Baloo_1.0.6.zip` from https://github.com/girish-dalvi/Baloo/releases/tag/1.0.6 I suggest the next release
- [x] Use only MAJOR.MINOR version number, corresponding to the version numbers inside the files; the semver.org style 3 numbers MAJOR.MINOR.PATCH is incompatible with the OpenType spec head table version key
- [x] Name files as in https://github.com/google/fonts/tree/master/ofl/baloo*/ 
- [x] Name file extensions as `.ttf` (or build CFF versions and use the `.otf` extension with them)

**Comment by girish-dalvi** [comment]
Fixed in 1.10
