### ISSUE TITLE
BalooBhaina-Odia

### ISSUE THREAD

**Issue by mkwiki** [girish-dalvi/Baloo#7]
ଦ୍ୟ, ର୍ତ୍ତ, ଦ୍ଧି and ର୍ଣ୍ଣା is broken
![gyan](https://cloud.githubusercontent.com/assets/16492140/13029326/48067ec4-d2af-11e5-9b57-466468b3b518.png)

**Comment by davelab6** [comment]
@girish-dalvi ping

**Comment by mkwiki** [comment]
ଦ୍ୟ, ର୍ତ୍ତ, ଦ୍ଧି, ର୍ଣ୍ଣା and ନ୍ଦି is broken
![update_baloobhaina_ndi_](https://cloud.githubusercontent.com/assets/16492140/14020099/8dd20df4-f1fb-11e5-8e50-20b806adee23.png)

**Comment by girish-dalvi** [comment]
The "DaYa" error has been fixed from our end and will be updated in the next font release. The other conjuncts do not break on our systems. We've checked on both Macintosh and Windows. Please use the latest file.

**Comment by davelab6** [comment]
@girish-dalvi no pressure, just curious - have you made any progress on this front? :)

**Comment by girish-dalvi** [comment]
Fixed in 1.443
