### ISSUE TITLE
MarkDown files are better with 1 sentence per line

### ISSUE THREAD

**Issue by davelab6** [girish-dalvi/Baloo#8]
Many of the changes in https://github.com/girish-dalvi/Baloo/commit/8c95e4d1fbe0633314fbf80f901fd01abe8fa53a are not to the text but to make paragraphs into single lines, instead of 1 sentence per line. 

This makes no difference to the HTML output, but makes diffs harder to parse in future.

**Comment by davelab6** [comment]
@girish-dalvi will you accept a pull request to revert the readme to 1 sentence per line?

**Comment by girish-dalvi** [comment]
@davelab6 Sure, Please send a pull request. Thanks.

**Comment by davelab6** [comment]
Thanks Girish!
